#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tinyxml2
Version  : 5.0.1
Release  : 3
URL      : https://github.com/leethomason/tinyxml2/archive/5.0.1.tar.gz
Source0  : https://github.com/leethomason/tinyxml2/archive/5.0.1.tar.gz
Summary  : simple, small, C++ XML parser
Group    : Development/Tools
License  : Zlib
Requires: tinyxml2-lib
BuildRequires : cmake

%description
The (default) Release configuration of this project builds a ready to use static library.
The Debug configuration of this project builds an executable console application that
executes all tests provided for tinyxml2 in the xmltest.cpp file.

%package dev
Summary: dev components for the tinyxml2 package.
Group: Development
Requires: tinyxml2-lib
Provides: tinyxml2-devel

%description dev
dev components for the tinyxml2 package.


%package lib
Summary: lib components for the tinyxml2 package.
Group: Libraries

%description lib
lib components for the tinyxml2 package.


%prep
%setup -q -n tinyxml2-5.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1513641927
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib
make VERBOSE=1  %{?_smp_mflags}
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pushd clr-build ; make test ; popd

%install
export SOURCE_DATE_EPOCH=1513641927
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib/cmake/tinyxml2/tinyxml2Config.cmake
/usr/lib/cmake/tinyxml2/tinyxml2Targets-relwithdebinfo.cmake
/usr/lib/cmake/tinyxml2/tinyxml2Targets.cmake

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libtinyxml2.so
/usr/lib64/pkgconfig/tinyxml2.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtinyxml2.so.5
/usr/lib64/libtinyxml2.so.5.0.1
